#step 1 
sudo: required
#install docker to our container
services:
  - docker

before_install:
  - docker build -t partidaa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true partidaa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-tutorial"
  env: "Docker-tutorial-env"
  bucket_name: "elasticbeanstalk-us-west-1-332143746536"
  bucket_path: "dokcer-tutorial"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
